// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rswfsvnbiciyqjyyuhjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzd2Zzdm5iaWNpeXFqeXl1aGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTU3OTcsImV4cCI6MjA3NDA5MTc5N30.lYD8tQbqFcJfAm2cZBwID7xcu-D5ixxxG2GIpp7Lmtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});